### ISSUE TITLE
[EPIC] Benchmark suite

### ISSUE THREAD

**Issue by Zorlin** [riffcc/lis#14]
I'm working on a benchmark suite/toy version of Lis called Recurso which uses Python and the Python libraries for Iroh to reimplement Lis in a compatible/alternative way.

We'll want to build the following test suite, ideally one directly in Lis as well:

- [ ] [Bench] Task Zero - Make a single file and folder in the root document
- [ ] [Bench] Lookup A - Measure lookup times for a single file and folder and sum them together for an initial score
- [ ] [Bench] Task A - Make 1000 directories in a single folder underneath the root document
- [ ] [Bench] Task B/Lookup B - Upload 1000 blobs and measure the time to upload
- [ ] [Bench] Task C/Lookup C - Insert 1000 blobs as file records into Task A's first folder
- [ ] [Bench] Lookup D - Measure lookup times from Lookup A after Task A+B are done and see if they are any faster or slower
- [ ] [Bench] Lookup E - Lookup and fetch a blob from Task C/Lookup C and measure the timing.
